# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_ajanlat_ugyfel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajanlat',
            options={'verbose_name': 'Ajánlat', 'verbose_name_plural': 'Ajánlatok'},
        ),
        migrations.RemoveField(
            model_name='ajanlat',
            name='agy_tipus',
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='kisallatok_szama',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='nagykoruak_szama',
            field=models.IntegerField(default=0),
        ),
    ]
