# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_ajanlat_erkezes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanlat',
            name='erkezes',
            field=models.DateTimeField(),
        ),
    ]
