# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20170422_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajanlatresz',
            old_name='ajanlat_id',
            new_name='ajanlat',
        ),
        migrations.RenameField(
            model_name='ajanlatresz',
            old_name='szallasresz_id',
            new_name='szallasresz',
        ),
    ]
