# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('tax_number', models.TextField(blank=True, null=True)),
                ('registration_number', models.TextField(blank=True, null=True)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.ClientType')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'verbose_name': 'Client',
            },
        ),
    ]
