# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgyTipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agy_tipus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlapAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agy_ar', models.IntegerField()),
                ('agy_tipus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.AgyTipus')),
            ],
        ),
        migrations.CreateModel(
            name='Szallas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szallas_nev', models.TextField()),
                ('szallas_cim', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SzallasJelleg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szallas_jelleg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SzallasResz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szallasresz_nev', models.TextField(blank=True, null=True)),
                ('agyak_szama', models.IntegerField()),
                ('potagyak_szama', models.IntegerField()),
                ('szobak_szama', models.IntegerField()),
                ('sajat_konyha', models.BooleanField()),
                ('szallas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Szallas')),
            ],
        ),
        migrations.CreateModel(
            name='SzallasReszTipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szallasresz_tipus', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SzallasTipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szallas_tipus', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='szallasresz',
            name='szallasresz_tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SzallasReszTipus'),
        ),
        migrations.AddField(
            model_name='szallas',
            name='szallas_jelleg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SzallasJelleg'),
        ),
        migrations.AddField(
            model_name='szallas',
            name='szallas_tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SzallasTipus'),
        ),
        migrations.AddField(
            model_name='alapar',
            name='szallas_tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SzallasTipus'),
        ),
    ]
