# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20170422_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajanlat',
            name='agy_tipus',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
