# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_bank_account_number'),
        ('reservations', '0003_ajanlat_agy_tipus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajanlat',
            name='ugyfel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client'),
            preserve_default=False,
        ),
    ]
