# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20170422_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajanlat',
            name='erkezes',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
