# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20170422_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjanlatResz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alap_agy_db', models.IntegerField()),
                ('alap_potagy_db', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ajánlatrész',
                'verbose_name_plural': 'Ajánlatrészek',
            },
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='egyejszakas_felar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_ebed_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_ebed_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_haromszori_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_haromszori_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_otszori_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_otszori_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_reggeli_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_reggeli_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_vacsora_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='etkezes_vacsora_db',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='ifa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='kisallat_felar_ej',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlat',
            name='tavozas',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajanlat',
            name='kisallatok_szama',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ajanlat',
            name='nagykoruak_szama',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajanlatresz',
            name='ajanlat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Ajanlat'),
        ),
        migrations.AddField(
            model_name='ajanlatresz',
            name='szallasresz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Szallas'),
        ),
    ]
