# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20170422_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanlatresz',
            name='szallasresz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SzallasResz'),
        ),
    ]
