# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20170422_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanlatresz',
            name='ajanlat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajanlat_ajanlatreszek', to='reservations.Ajanlat'),
        ),
        migrations.AlterField(
            model_name='ajanlatresz',
            name='szallasresz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.SzallasResz'),
        ),
    ]
