# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20170422_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanlat',
            name='ugyfel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ugyfeltext', to='clients.Client'),
        ),
    ]
