# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20170422_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanlat',
            name='ugyfel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ugyfel', to='clients.Client'),
        ),
    ]
