# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Client type',
                'verbose_name_plural': 'Client types',
            },
        ),
    ]
