# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20170415_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_birthdate', to='clients.Client')),
            ],
            options={
                'verbose_name_plural': 'Birth Dates',
                'verbose_name': 'Birth Date',
            },
        ),
    ]
