# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='country',
            new_name='country_code',
        ),
    ]
