# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20170415_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_emails', to='clients.Client'),
        ),
    ]
